# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-21 18:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("graduate_students", "0002_auto_20150611_1532")]

    operations = [
        migrations.AlterField(
            model_name="graduatestudent",
            name="status",
            field=models.CharField(
                choices=[
                    (b"P", b"Pending Student (not yet accepted)"),
                    (b"S", b"Current Student"),
                    (b"AW", b"Authorized Withdrawl"),
                    (b"CW", b"Compulsary Withdrawl"),
                    (b"VW", b"Voluntary Withdrawl"),
                    (b"G", b"Graduated"),
                    (b"C", b"Completed (Pre-MSc)"),
                ],
                default=b"P",
                max_length=2,
            ),
        )
    ]
