# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-11-10 19:39
from __future__ import unicode_literals

import django.core.files.storage
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("graduate_students", "0003_auto_20151221_1217")]

    operations = [
        migrations.CreateModel(
            name="Paperwork",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="creation time"
                    ),
                ),
                (
                    "modified",
                    models.DateTimeField(
                        auto_now=True, verbose_name="last modification time"
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        storage=django.core.files.storage.FileSystemStorage(
                            location="/dev/null"
                        ),
                        upload_to="%Y/%m/%d",
                    ),
                ),
                ("description", models.CharField(blank=True, max_length=250)),
                (
                    "graduate_student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="graduate_students.GraduateStudent",
                    ),
                ),
            ],
            options={"abstract": False},
        )
    ]
