# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-02 15:55
from __future__ import unicode_literals

import django.db.models.deletion
import graduate_students.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("graduate_students", "0004_paperwork")]

    operations = [
        migrations.AlterModelOptions(
            name="funding",
            options={
                "base_manager_name": "objects",
                "ordering": ("start_date", "end_date"),
                "verbose_name_plural": "funding",
            },
        ),
        migrations.AlterModelOptions(
            name="fundingsource",
            options={"base_manager_name": "objects", "ordering": ("ordering", "name")},
        ),
        migrations.AlterModelOptions(
            name="graduatestudent",
            options={
                "base_manager_name": "objects",
                "ordering": ("-program", "status", "person"),
            },
        ),
        migrations.AlterModelOptions(
            name="milestone",
            options={
                "base_manager_name": "objects",
                "get_latest_by": "date",
                "ordering": ["date"],
            },
        ),
        migrations.AlterModelOptions(
            name="milestonetype",
            options={"base_manager_name": "objects", "ordering": ["name"]},
        ),
        migrations.AlterField(
            model_name="funding",
            name="source",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="graduate_students.FundingSource",
            ),
        ),
        migrations.AlterField(
            model_name="graduatestudent",
            name="person",
            field=models.ForeignKey(
                help_text='Only people with the "gradstudent" flag are shown. \n                                    You should not change this after it has been set.',
                on_delete=django.db.models.deletion.PROTECT,
                to="people.Person",
            ),
        ),
        migrations.AlterField(
            model_name="paperwork",
            name="file",
            field=models.FileField(
                storage=graduate_students.storage.PaperworkFileSystemStorage(
                    location="/Volumes/ExtHome/__storage/stats/gradstudent-paperwork"
                ),
                upload_to="%Y/%m/%d",
            ),
        ),
    ]
